
@baseUrl= http://localhost:7000/api/usuarios

POST {{baseUrl}} HTTP/1.1
content-type: application/json

{
  "name": "John Doe",
  "email": "john.doe@email.com",
  "password": "12345678",
  "urlPhoto": "https://randomuser.me/api/portraits/men/90.jpg"
}



###
GET {{baseUrl}} HTTP/1.1

@userId= 86641ee7-73af-4dfb-be01-e07972eb09e6

###
GET {{baseUrl}}/{{userId}} HTTP/1.1

###
PATCH {{baseUrl}}/{{userId}} HTTP/1.1
content-type: application/json

{
  "name": "John Doe Updated"
}


###
DELETE {{baseUrl}}/{{userId}} HTTP/1.1
